/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package writedata;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class WritedataUI extends javax.swing.JFrame {

    /**
     * Creates new form WritedataUI
     */
    public java.io.File file;

    public WritedataUI() {
        initComponents();
                 file = new java.io.File("D:/scores.txt");
         if(file.exists()){
             System.out.println("File already exists! ");
             System.exit(0);    
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        nLabel = new javax.swing.JLabel();
        TextFieldname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mList = new javax.swing.JList();
        mjLabel1 = new javax.swing.JLabel();
        eButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        mRadioButton = new javax.swing.JRadioButton();
        fRadioButton = new javax.swing.JRadioButton();
        rButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Please complete the following data fileds");

        nLabel.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        nLabel.setForeground(new java.awt.Color(0, 51, 153));
        nLabel.setText("Name");

        mList.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        mList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Fianace", "Information Management", "Engish", "Chinese", "Math" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(mList);

        mjLabel1.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        mjLabel1.setForeground(new java.awt.Color(0, 51, 153));
        mjLabel1.setText("Major");

        eButton.setFont(new java.awt.Font("新細明體", 1, 14)); // NOI18N
        eButton.setForeground(new java.awt.Color(0, 51, 204));
        eButton.setText("Enter");
        eButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eButtonMouseClicked(evt);
            }
        });

        cButton.setFont(new java.awt.Font("新細明體", 1, 14)); // NOI18N
        cButton.setForeground(new java.awt.Color(0, 51, 204));
        cButton.setText("Clear");
        cButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cButtonMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Here is the data you entered");

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane2.setViewportView(TextArea);

        buttonGroup.add(mRadioButton);
        mRadioButton.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        mRadioButton.setForeground(new java.awt.Color(0, 51, 153));
        mRadioButton.setText("Male");
        mRadioButton.setName("Male"); // NOI18N

        buttonGroup.add(fRadioButton);
        fRadioButton.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        fRadioButton.setForeground(new java.awt.Color(0, 51, 153));
        fRadioButton.setText("Female");
        fRadioButton.setName("Female"); // NOI18N

        rButton.setFont(new java.awt.Font("新細明體", 1, 14)); // NOI18N
        rButton.setForeground(new java.awt.Color(0, 51, 204));
        rButton.setText("Read");
        rButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(nLabel)
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fRadioButton)
                                        .addComponent(mRadioButton))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(eButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(115, 115, 115)
                                            .addComponent(rButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(38, 38, 38)))
                                    .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mRadioButton)
                            .addComponent(mjLabel1))
                        .addGap(8, 8, 8)
                        .addComponent(fRadioButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eButton)
                    .addComponent(cButton)
                    .addComponent(rButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eButtonMouseClicked
        String name = new String();
        String major = new String();
        String gender = new String();

        name = TextFieldname.getText();

        if(mRadioButton.isSelected())
             gender = mRadioButton.getName();
        else if(fRadioButton.isSelected())
             gender = fRadioButton.getName();

        major = (String)mList.getSelectedValue();
        TextArea.setText("name: "+name+"\ngender: "+gender+"\nmajor: "+major );
        
        java.io.PrintWriter output = null;
        try 
         {
              output = new java.io.PrintWriter(new FileWriter("D:/scores.txt",true));
             
              output.println("name: "+name+"\ngender: "+gender+"\nmajor: "+major );
              output.close();
        } catch (IOException ex) {
            Logger.getLogger(Writedata.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            output.close();
        }
    }//GEN-LAST:event_eButtonMouseClicked

    private void cButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cButtonMouseClicked
        TextArea.setText("");
        TextFieldname.setText("");      
        buttonGroup.clearSelection();
        mList.setSelectedIndex(-1);
    }//GEN-LAST:event_cButtonMouseClicked

    private void rButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rButtonMouseClicked
        try {
            TextArea.read(new FileReader(file.getAbsolutePath()),null);
        } catch (IOException ex) {
            Logger.getLogger(WritedataUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WritedataUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WritedataUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WritedataUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WritedataUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WritedataUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea;
    private javax.swing.JTextField TextFieldname;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton cButton;
    private javax.swing.JButton eButton;
    private javax.swing.JRadioButton fRadioButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList mList;
    private javax.swing.JRadioButton mRadioButton;
    private javax.swing.JLabel mjLabel1;
    private javax.swing.JLabel nLabel;
    private javax.swing.JButton rButton;
    // End of variables declaration//GEN-END:variables
}
